version: '3.8'

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: evaluapp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-evaluapp_db}
      MYSQL_USER: ${DB_USER:-evaluapp_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-evaluapp_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - evaluapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Aplicación Spring Boot
  app:
    build:
      context: .
      target: builder
    container_name: evaluapp-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://db:3306/${DB_NAME:-evaluapp_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USERNAME=${DB_USER:-evaluapp_user}
      - DB_PASSWORD=${DB_PASSWORD:-evaluapp_password}
      - JWT_SECRET=${JWT_SECRET:-your-secure-jwt-secret-key}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8080:8080"
    networks:
      - evaluapp-network
    restart: unless-stopped

  # Adminer para gestión de base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: evaluapp-adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - evaluapp-network

networks:
  evaluapp-network:
    driver: bridge

volumes:
  mysql_data:
